const colorVar = (name) => `rgb(var(${name}) / <alpha-value>)`

/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  safelist: [
    'hover:border-teal-300/80', 'hover:border-cyan-300/80', 'hover:border-[#ff716c]/80', 'hover:border-emerald-300/80',
    'focus:border-teal-300/40', 'focus:border-cyan-300/40', 'focus:border-[#ff716c]/40', 'focus:border-emerald-300/40',
    'focus:ring-teal-300/10', 'focus:ring-cyan-300/10', 'focus:ring-[#ff716c]/10', 'focus:ring-emerald-300/10',
    'border-teal-300/20', 'border-cyan-300/20', 'border-[#ff716c]/20', 'border-emerald-300/20',
    'bg-teal-500/10', 'bg-cyan-500/10', 'bg-[#ff716c]/10', 'bg-emerald-500/10',
    'bg-teal-400/10', 'bg-cyan-400/10', 'bg-[#ff716c]/10', 'bg-emerald-400/10',
    'bg-teal-400/5', 'bg-cyan-400/5', 'bg-[#ff716c]/5', 'bg-emerald-400/5',
    'text-teal-300', 'text-cyan-300', 'text-[#ff9e9a]', 'text-emerald-300',
    'text-teal-200', 'text-cyan-200', 'text-[#ffbdb8]', 'text-emerald-200',
    'bg-teal-300', 'bg-cyan-300', 'bg-[#ff716c]', 'bg-emerald-300',
    'from-teal-300', 'from-cyan-300', 'from-[#ff9e9a]', 'from-emerald-300',
    'to-teal-500', 'to-cyan-500', 'to-[#ff716c]', 'to-emerald-500',
  ],
  theme: {
    extend: {
      colors: {
        'on-surface': colorVar('--color-on-surface'),
        'primary-dim': colorVar('--color-primary-dim'),
        'secondary-fixed-dim': colorVar('--color-secondary-fixed-dim'),
        'on-error-container': colorVar('--color-on-error-container'),
        'on-tertiary-fixed-variant': colorVar('--color-on-tertiary-fixed-variant'),
        'on-tertiary-fixed': colorVar('--color-on-tertiary-fixed'),
        'on-tertiary-container': colorVar('--color-on-tertiary-container'),
        'inverse-on-surface': colorVar('--color-inverse-on-surface'),
        'on-tertiary': colorVar('--color-on-tertiary'),
        'surface': colorVar('--color-surface'),
        'on-primary-container': colorVar('--color-on-primary-container'),
        'error-container': colorVar('--color-error-container'),
        'secondary-fixed': colorVar('--color-secondary-fixed'),
        'tertiary': colorVar('--color-tertiary'),
        'error-dim': colorVar('--color-error-dim'),
        'surface-bright': colorVar('--color-surface-bright'),
        'tertiary-container': colorVar('--color-tertiary-container'),
        'primary': colorVar('--color-primary'),
        'warning': colorVar('--color-warning'),
        'background': colorVar('--color-background'),
        'surface-container': colorVar('--color-surface-container'),
        'tertiary-fixed': colorVar('--color-tertiary-fixed'),
        'surface-dim': colorVar('--color-surface-dim'),
        'secondary': colorVar('--color-secondary'),
        'surface-variant': colorVar('--color-surface-variant'),
        'on-primary': colorVar('--color-on-primary'),
        'error': colorVar('--color-error'),
        'on-primary-fixed': colorVar('--color-on-primary-fixed'),
        'primary-fixed': colorVar('--color-primary-fixed'),
        'inverse-primary': colorVar('--color-inverse-primary'),
        'tertiary-fixed-dim': colorVar('--color-tertiary-fixed-dim'),
        'surface-container-highest': colorVar('--color-surface-container-highest'),
        'surface-container-lowest': colorVar('--color-surface-container-lowest'),
        'on-secondary-fixed': colorVar('--color-on-secondary-fixed'),
        'on-primary-fixed-variant': colorVar('--color-on-primary-fixed-variant'),
        'secondary-dim': colorVar('--color-secondary-dim'),
        'on-secondary-fixed-variant': colorVar('--color-on-secondary-fixed-variant'),
        'on-secondary-container': colorVar('--color-on-secondary-container'),
        'on-secondary': colorVar('--color-on-secondary'),
        'inverse-surface': colorVar('--color-inverse-surface'),
        'primary-fixed-dim': colorVar('--color-primary-fixed-dim'),
        'outline-variant': colorVar('--color-outline-variant'),
        'on-background': colorVar('--color-on-background'),
        'surface-container-high': colorVar('--color-surface-container-high'),
        'secondary-container': colorVar('--color-secondary-container'),
        'on-surface-variant': colorVar('--color-on-surface-variant'),
        'outline': colorVar('--color-outline'),
        'surface-container-low': colorVar('--color-surface-container-low'),
        'surface-tint': colorVar('--color-surface-tint'),
        'primary-container': colorVar('--color-primary-container'),
        'on-error': colorVar('--color-on-error'),
      },
      fontFamily: {
        headline: ['Plus Jakarta Sans', 'sans-serif'],
        body: ['Manrope', 'sans-serif'],
        label: ['Manrope', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '1rem',
        lg: '2rem',
        xl: '3rem',
        full: '9999px',
      },
    },
  },
  plugins: [],
}
