const colorVar = (name) => `rgb(var(${name}) / <alpha-value>)`

/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        'on-surface': colorVar('--color-on-surface'),
        'primary-dim': colorVar('--color-primary-dim'),
        'secondary-fixed-dim': colorVar('--color-secondary-fixed-dim'),
        'on-error-container': colorVar('--color-on-error-container'),
        'on-tertiary-fixed-variant': colorVar('--color-on-tertiary-fixed-variant'),
        'on-tertiary-fixed': colorVar('--color-on-tertiary-fixed'),
        'on-tertiary-container': colorVar('--color-on-tertiary-container'),
        'inverse-on-surface': colorVar('--color-inverse-on-surface'),
        'on-tertiary': colorVar('--color-on-tertiary'),
        'surface': colorVar('--color-surface'),
        'on-primary-container': colorVar('--color-on-primary-container'),
        'error-container': colorVar('--color-error-container'),
        'secondary-fixed': colorVar('--color-secondary-fixed'),
        'tertiary': colorVar('--color-tertiary'),
        'error-dim': colorVar('--color-error-dim'),
        'surface-bright': colorVar('--color-surface-bright'),
        'tertiary-container': colorVar('--color-tertiary-container'),
        'primary': colorVar('--color-primary'),
        'warning': colorVar('--color-warning'),
        'background': colorVar('--color-background'),
        'surface-container': colorVar('--color-surface-container'),
        'tertiary-fixed': colorVar('--color-tertiary-fixed'),
        'surface-dim': colorVar('--color-surface-dim'),
        'secondary': colorVar('--color-secondary'),
        'surface-variant': colorVar('--color-surface-variant'),
        'on-primary': colorVar('--color-on-primary'),
        'error': colorVar('--color-error'),
        'on-primary-fixed': colorVar('--color-on-primary-fixed'),
        'primary-fixed': colorVar('--color-primary-fixed'),
        'inverse-primary': colorVar('--color-inverse-primary'),
        'tertiary-fixed-dim': colorVar('--color-tertiary-fixed-dim'),
        'surface-container-highest': colorVar('--color-surface-container-highest'),
        'surface-container-lowest': colorVar('--color-surface-container-lowest'),
        'on-secondary-fixed': colorVar('--color-on-secondary-fixed'),
        'on-primary-fixed-variant': colorVar('--color-on-primary-fixed-variant'),
        'secondary-dim': colorVar('--color-secondary-dim'),
        'on-secondary-fixed-variant': colorVar('--color-on-secondary-fixed-variant'),
        'on-secondary-container': colorVar('--color-on-secondary-container'),
        'on-secondary': colorVar('--color-on-secondary'),
        'inverse-surface': colorVar('--color-inverse-surface'),
        'primary-fixed-dim': colorVar('--color-primary-fixed-dim'),
        'outline-variant': colorVar('--color-outline-variant'),
        'on-background': colorVar('--color-on-background'),
        'surface-container-high': colorVar('--color-surface-container-high'),
        'secondary-container': colorVar('--color-secondary-container'),
        'on-surface-variant': colorVar('--color-on-surface-variant'),
        'outline': colorVar('--color-outline'),
        'surface-container-low': colorVar('--color-surface-container-low'),
        'surface-tint': colorVar('--color-surface-tint'),
        'primary-container': colorVar('--color-primary-container'),
        'on-error': colorVar('--color-on-error'),
      },
      fontFamily: {
        headline: ['var(--teal-font-headline)'],
        body: ['var(--teal-font-body)'],
        label: ['var(--teal-font-body)'],
      },
      borderRadius: {
        sm: '0.375rem',
        DEFAULT: '0.5rem',
        md: '0.625rem',
        lg: '0.75rem',
        xl: '1rem',
        '2xl': '1.25rem',
        '3xl': '1.5rem',
        full: '9999px',
      },
    },
  },
  plugins: [],
}
