/**
 * Canonical semantic token source. Generated consumers are tokens.css,
 * tailwind.preset.js, and the documentation token metadata.
 */
export const colorTokens = {
  'teal-color-on-surface': { light: [14, 44, 44], dark: [232, 246, 243] },
  'teal-color-primary-dim': { light: [0, 94, 96], dark: [45, 212, 191] },
  'teal-color-secondary-fixed-dim': { light: [6, 90, 96], dark: [45, 212, 191] },
  'teal-color-on-error-container': { light: [136, 19, 55], dark: [255, 200, 204] },
  'teal-color-on-tertiary-fixed-variant': { light: [2, 54, 54], dark: [0, 0, 0] },
  'teal-color-on-tertiary-fixed': { light: [2, 54, 54], dark: [0, 0, 0] },
  'teal-color-on-tertiary-container': { light: [2, 54, 54], dark: [255, 255, 255] },
  'teal-color-inverse-on-surface': { light: [236, 244, 242], dark: [15, 46, 46] },
  'teal-color-on-tertiary': { light: [255, 255, 255], dark: [0, 0, 0] },
  'teal-color-surface': { light: [255, 255, 255], dark: [9, 35, 36] },
  'teal-color-on-primary-container': { light: [2, 54, 54], dark: [255, 255, 255] },
  'teal-color-error-container': { light: [255, 228, 230], dark: [127, 29, 29] },
  'teal-color-secondary-fixed': { light: [224, 245, 244], dark: [10, 46, 46] },
  'teal-color-tertiary': { light: [0, 115, 74], dark: [52, 211, 153] },
  'teal-color-error-dim': { light: [190, 18, 60], dark: [248, 113, 113] },
  'teal-color-surface-bright': { light: [255, 255, 255], dark: [33, 73, 71] },
  'teal-color-tertiary-container': { light: [209, 250, 229], dark: [6, 78, 59] },
  'teal-color-primary': { light: [0, 106, 108], dark: [45, 212, 191] },
  'teal-color-background': { light: [239, 246, 244], dark: [3, 22, 23] },
  'teal-color-surface-container': { light: [248, 252, 250], dark: [14, 46, 46] },
  'teal-color-tertiary-fixed': { light: [167, 243, 208], dark: [45, 212, 191] },
  'teal-color-surface-dim': { light: [230, 240, 238], dark: [2, 26, 26] },
  'teal-color-secondary': { light: [6, 90, 96], dark: [45, 212, 191] },
  'teal-color-surface-variant': { light: [230, 240, 238], dark: [20, 58, 58] },
  'teal-color-on-primary': { light: [255, 255, 255], dark: [0, 0, 0] },
  'teal-color-error': { light: [200, 30, 65], dark: [251, 113, 133] },
  'teal-color-warning': { light: [170, 75, 0], dark: [251, 191, 36] },
  'teal-color-on-primary-fixed': { light: [255, 255, 255], dark: [0, 0, 0] },
  'teal-color-primary-fixed': { light: [0, 106, 108], dark: [45, 212, 191] },
  'teal-color-inverse-primary': { light: [224, 245, 244], dark: [0, 100, 102] },
  'teal-color-tertiary-fixed-dim': { light: [52, 211, 153], dark: [45, 212, 191] },
  'teal-color-surface-container-highest': { light: [234, 242, 240], dark: [27, 64, 63] },
  'teal-color-surface-container-lowest': { light: [255, 255, 255], dark: [0, 0, 0] },
  'teal-color-on-secondary-fixed': { light: [2, 54, 54], dark: [255, 255, 255] },
  'teal-color-on-primary-fixed-variant': { light: [255, 255, 255], dark: [0, 0, 0] },
  'teal-color-secondary-dim': { light: [11, 82, 87], dark: [45, 212, 191] },
  'teal-color-on-secondary-fixed-variant': { light: [255, 255, 255], dark: [0, 0, 0] },
  'teal-color-on-secondary-container': { light: [2, 54, 54], dark: [255, 255, 255] },
  'teal-color-on-secondary': { light: [255, 255, 255], dark: [0, 0, 0] },
  'teal-color-inverse-surface': { light: [14, 44, 44], dark: [232, 246, 243] },
  'teal-color-primary-fixed-dim': { light: [0, 106, 108], dark: [45, 212, 191] },
  'teal-color-outline-variant': { light: [188, 207, 203], dark: [57, 88, 87] },
  'teal-color-on-background': { light: [14, 44, 44], dark: [232, 246, 243] },
  'teal-color-surface-container-high': { light: [241, 247, 245], dark: [20, 54, 54] },
  'teal-color-secondary-container': { light: [224, 245, 244], dark: [0, 100, 102] },
  'teal-color-on-surface-variant': { light: [64, 92, 90], dark: [138, 176, 173] },
  'teal-color-outline': { light: [100, 128, 125], dark: [112, 142, 140] },
  'teal-color-surface-container-low': { light: [252, 254, 253], dark: [10, 40, 40] },
  'teal-color-surface-tint': { light: [0, 106, 108], dark: [45, 212, 191] },
  'teal-color-primary-container': { light: [224, 245, 244], dark: [0, 100, 102] },
  'teal-color-on-error': { light: [255, 255, 255], dark: [0, 0, 0] },
}

export const sharedTokens = {
  '--teal-font-body': "'Manrope', ui-sans-serif, system-ui, sans-serif",
  '--teal-font-headline': "'Plus Jakarta Sans', ui-sans-serif, system-ui, sans-serif",
  '--teal-radius-control': '1rem',
  '--teal-radius-surface': '1.25rem',
  '--teal-radius-pill': '9999px',
  '--teal-border-subtle': 'color-mix(in srgb, var(--teal-color-outline-variant) 55%, transparent)',
  '--teal-border-strong': 'var(--teal-color-outline)',
  '--teal-focus-ring': '0 0 0 2px var(--teal-color-surface), 0 0 0 4px var(--teal-color-primary)',
  '--teal-shadow-raised': '0 1px 2px rgba(0, 35, 36, 0.06), 0 12px 32px -20px rgba(0, 84, 84, 0.32)',
  '--teal-shadow-card': 'var(--teal-shadow-raised)',
  '--teal-shadow-overlay': '0 2px 6px rgba(0, 20, 21, 0.12), 0 24px 64px -20px rgba(0, 20, 21, 0.42)',
  '--teal-icon-xs': '0.875rem',
  '--teal-icon-sm': '1rem',
  '--teal-icon-md': '1.25rem',
  '--teal-icon-lg': '1.5rem',
  '--teal-icon-xl': '2rem',
  '--teal-motion-fast': '150ms',
  '--teal-motion-standard': '200ms',
  '--teal-z-popover': '40',
  '--teal-z-overlay': '50',
  '--teal-z-dialog': '51',
  '--teal-z-toast': '60',
  '--teal-z-tooltip': '70',
}

export const documentationColors = [
  { name: 'Primary', token: '--teal-color-primary', bg: 'bg-teal-primary', fg: 'text-teal-on-primary' },
  { name: 'Success', token: '--teal-color-tertiary', bg: 'bg-teal-tertiary', fg: 'text-teal-on-tertiary' },
  { name: 'Warning', token: '--teal-color-warning', bg: 'bg-teal-warning', fg: 'text-black' },
  { name: 'Danger', token: '--teal-color-error', bg: 'bg-teal-error', fg: 'text-teal-on-error' },
  { name: 'Surface', token: '--teal-color-surface-container', bg: 'bg-teal-surface-container', fg: 'text-teal-on-surface' },
  { name: 'Elevated surface', token: '--teal-color-surface-container-high', bg: 'bg-teal-surface-container-high', fg: 'text-teal-on-surface' },
]

export const documentationVisualTokens = [
  { name: 'Control radius', token: '--teal-radius-control' },
  { name: 'Surface radius', token: '--teal-radius-surface' },
  { name: 'Pill radius', token: '--teal-radius-pill' },
  { name: 'Subtle border', token: '--teal-border-subtle' },
  { name: 'Strong border', token: '--teal-border-strong' },
  { name: 'Focus ring', token: '--teal-focus-ring' },
  { name: 'Raised elevation', token: '--teal-shadow-raised' },
  { name: 'Overlay elevation', token: '--teal-shadow-overlay' },
  { name: 'Extra-small icon', token: '--teal-icon-xs' },
  { name: 'Small icon', token: '--teal-icon-sm' },
  { name: 'Medium icon', token: '--teal-icon-md' },
  { name: 'Large icon', token: '--teal-icon-lg' },
  { name: 'Extra-large icon', token: '--teal-icon-xl' },
  { name: 'Fast motion', token: '--teal-motion-fast' },
  { name: 'Standard motion', token: '--teal-motion-standard' },
]

export const contrastPairs = [
  ['teal-color-on-surface', 'teal-color-surface'],
  ['teal-color-on-surface-variant', 'teal-color-surface-variant'],
  ['teal-color-on-background', 'teal-color-background'],
  ['teal-color-on-primary', 'teal-color-primary'],
  ['teal-color-on-primary-container', 'teal-color-primary-container'],
  ['teal-color-on-primary-fixed', 'teal-color-primary-fixed'],
  ['teal-color-on-primary-fixed-variant', 'teal-color-primary-fixed-dim'],
  ['teal-color-on-secondary', 'teal-color-secondary'],
  ['teal-color-on-secondary-container', 'teal-color-secondary-container'],
  ['teal-color-on-secondary-fixed', 'teal-color-secondary-fixed'],
  ['teal-color-on-secondary-fixed-variant', 'teal-color-secondary-fixed-dim'],
  ['teal-color-on-tertiary', 'teal-color-tertiary'],
  ['teal-color-on-tertiary-container', 'teal-color-tertiary-container'],
  ['teal-color-on-tertiary-fixed', 'teal-color-tertiary-fixed'],
  ['teal-color-on-tertiary-fixed-variant', 'teal-color-tertiary-fixed-dim'],
  ['teal-color-on-error', 'teal-color-error'],
  ['teal-color-on-error-container', 'teal-color-error-container'],
  ['teal-color-inverse-on-surface', 'teal-color-inverse-surface'],
  ['teal-color-inverse-primary', 'teal-color-inverse-surface'],
]
