import { mkdir, readFile, writeFile } from 'node:fs/promises'
import { resolve } from 'node:path'
import { colorTokens, contrastPairs, documentationColors, documentationVisualTokens, sharedTokens } from '../token-source.mjs'

const packageRoot = resolve(import.meta.dirname, '..')
const workspaceRoot = resolve(packageRoot, '../..')
const cssPath = resolve(packageRoot, 'src/tokens.css')
const presetPath = resolve(packageRoot, 'tailwind.preset.js')
const docsPath = resolve(workspaceRoot, 'apps/docs/src/generated/tokens.js')
const contrastPath = resolve(packageRoot, 'test/tokens.generated.ts')

function cssVariables(values) {
  return Object.entries(values)
    .map(([name, value]) => `  ${name.startsWith('--') ? name : `--${name}`}: ${Array.isArray(value) ? value.join(' ') : value};`)
    .join('\n')
}

function renderCss() {
  const light = Object.fromEntries(
    Object.entries(colorTokens).map(([name, token]) => [name, `rgb(${token.light.join(' ')})`]),
  )
  const dark = Object.fromEntries(
    Object.entries(colorTokens).map(([name, token]) => [name, `rgb(${token.dark.join(' ')})`]),
  )
  return `/* Generated by scripts/generate-tokens.mjs. Do not edit directly. */
/* Teal design tokens: Minimal Teal palette, light and dark. */
:root {
  color-scheme: light;
${cssVariables(light)}
${cssVariables(sharedTokens)}
}

html.dark {
  color-scheme: dark;
${cssVariables(dark)}
}
`
}

function renderPreset() {
  const colors = Object.fromEntries(
    Object.keys(colorTokens).map((name) => [
      name.replace(/^teal-color-/, 'teal-'),
      `color-mix(in srgb, var(--${name}) calc(<alpha-value> * 100%), transparent)`,
    ]),
  )
  return `/* Generated by scripts/generate-tokens.mjs. Do not edit directly. */
/** @type {import('tailwindcss').Config} */
export default {
  theme: {
    extend: {
      colors: ${JSON.stringify(colors, null, 8)},
      fontFamily: {
        'teal-headline': ['var(--teal-font-headline)'],
        'teal-body': ['var(--teal-font-body)'],
        'teal-label': ['var(--teal-font-body)'],
      },
      borderRadius: {
        'teal-control': 'var(--teal-radius-control)',
        'teal-surface': 'var(--teal-radius-surface)',
        'teal-pill': 'var(--teal-radius-pill)',
      },
      boxShadow: {
        'teal-raised': 'var(--teal-shadow-raised)',
        'teal-overlay': 'var(--teal-shadow-overlay)',
      },
    },
  },
  plugins: [],
}
`
}

const docs = `/* Generated by packages/teal/scripts/generate-tokens.mjs. Do not edit directly. */
export default ${JSON.stringify({ colors: documentationColors, contrastPairs, visualTokens: documentationVisualTokens }, null, 2)}
`
const contrast = `/* Generated by packages/teal/scripts/generate-tokens.mjs. Do not edit directly. */
export const contrastPairs = ${JSON.stringify(contrastPairs)} as const
`
const outputs = new Map([
  [cssPath, renderCss()],
  [presetPath, renderPreset()],
  [docsPath, docs],
  [contrastPath, contrast],
])
const check = process.argv.includes('--check')

if (check) {
  const drift = []
  for (const [path, expected] of outputs) {
    let actual
    try {
      actual = await readFile(path, 'utf8')
    } catch {
      drift.push(path)
      continue
    }
    if (actual !== expected) drift.push(path)
  }
  if (drift.length) {
    throw new Error(`Generated token outputs are stale:\n${drift.join('\n')}\nRun npm run generate:tokens.`)
  }
} else {
  await mkdir(resolve(docsPath, '..'), { recursive: true })
  for (const [path, contents] of outputs) await writeFile(path, contents)
  console.log(`Generated ${outputs.size} token outputs`)
}
