/* Generated by packages/teal/scripts/generate-tokens.mjs. Do not edit directly. */
export const contrastPairs = [["color-on-surface-variant","color-background"],["color-on-primary","color-primary"],["color-tertiary","color-surface-container"],["color-warning","color-surface-container"],["color-error","color-background"],["color-on-error","color-error-dim"]] as const
